/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:6b8da8bd-e4d4-4151-9cda-6fa5827fe7ae",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_xsIiAA9Eu",
    "aws_user_pools_web_client_id": "495ar0lpv3a1sanev7icpp7nvq",
    "oauth": {}
};


export default awsmobile;
